### ISSUE TITLE
Improved directory changing

### ISSUE THREAD

**Issue by Mateiadrielrafael** [saurabhdaware/projectman#33] opened 2020-01-29 11:02 UTC
It would be useful to have a `pm cd` alias for `cd $(pm getpath)`

**Comment by saurabhdaware** [comment] 2020-01-29 11:14
I would love to have it as well but as mentioned in Issue #7 , It is too complicated to implement.

`cd $(pm getpath)` is kind of a hack. `pm getpath` returns the directory so the command is executed as `cd /dir/to/project`. 

Here `cd` is a default terminal command so I can't really create alias directly.

**Comment by Mateiadrielrafael** [comment] 2020-01-29 16:14
I think even allowing something like `pm switch <project> <command>` (eg: `pm switch foo cd`) would look better, but I haven't looked into the code so I'm not sure if you can do it, I mean, it's ok if it's not there, the interpolation is good enough

**Comment by saurabhdaware** [comment] 2020-01-30 06:08
even `pm switch foo cd` will have the same problem with implementation. The problem is [we cannot execute cd from a program](https://stackoverflow.com/questions/15629923/nodejs-exec-does-not-work-for-cd-shell-cmd) 

With the current approach, we are not really executing `cd` instead we are just giving a value to `cd`

I'm closing this for now but do let me know if you have any way to work around this problem since this has been one of the most asked features

**Closed by saurabhdaware** 2020-01-30 06:08 UTC

**Comment by Mateiadrielrafael** [comment] 2020-01-30 10:08
@saurabhdaware What about [chdir](https://nodejs.org/api/process.html#process_process_chdir_directory)

**Comment by saurabhdaware** [comment] 2020-02-01 12:20
process.chdir has same effect as running child process and running cd over it. It only changes directory for that particular node program environment and not the directory on command line
